sudo: false
language: python
python:
  - "3.4"

# env:
env:
 - TOX_ENV=coveralls

# command to install dependencies
install:
  - "pip3 install tox"

# command to run tests
script:
  - tox -e $TOX_ENV

# notifications:
notifications:
  email:
    recipients:
      - simone.campagna11@gmail.com
    on_success: change
    on_failure: always

# branches:
branches:
  only:
    - master

