sudo: false
language: python
python:
  - "3.4"

# env:
env:
 - TOX_ENV=coverage

# command to install dependencies
install:
  - "pip3 install tox"
  - "pip3 install coveralls"


# command to run tests
script:
  - tox -e $TOX_ENV

after_success:
  - coveralls --rcfile=.tox/coverage/tox.coveragerc

# notifications:
notifications:
  email:
    recipients:
      - simone.campagna11@gmail.com
    on_success: change
    on_failure: always

# branches:
branches:
  only:
    - master

